version: "3.9"

services:
  # Laravel app (PHP-FPM)
  app_test:
    build:
      context: ./backend
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - ./backend:/var/www/
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini

    networks:
      - app-test-network
    depends_on:
      - mysql_test_db
    environment:
      - DB_HOST=mysql_test_db
      - DB_PORT=${MYSQL_PORT}
      - DB_DATABASE=${MYSQL_DATABASE}
      - DB_USERNAME=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}

  # Nginx web server for Laravel
  nginx:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./backend/:/var/www
      - ./docker/nginx/config.d:/etc/nginx/conf.d
    networks:
      - app-test-network
    depends_on:
      - app_test

  # MySQL database
  mysql_test_db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
 
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-test-network

  # phpMyAdmin (optional)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql_test_db
      PMA_PORT: 3306
    depends_on:
      - mysql_test_db
    networks:
      - app-test-network

  # React frontend
  frontend:
    build:
      context: ./frontend
    container_name: react_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_URL=http://localhost:8080/api
    depends_on:
      -   app_test
    networks:
      - app-test-network

networks:
  app-test-network:
    driver: bridge

volumes:
  db_data:
